# Actividad Evaluable: Limpieza de datos
## Juan Manuel Torres Rottonda - A01800476

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("bike_buyers.csv")

In [3]:
df.head()

,ID,Marital Status,Gender,Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike
0,12591,Married,Female,"30,000",4.0,Graduate Degree,Clerical,Yes,0.0,0-1 Miles,Europe,45.0,No
1,14058,Single,Male,"70,000",0.0,Bachelors,Professional,No,1.0,5-10 Miles,Pacific,41.0,Yes
2,23962,Married,Female,"10,000",0.0,Partial High School,Manual,Yes,2.0,1-2 Miles,Europe,32.0,No
3,23419,Single,Female,"70,000",5.0,Bachelors,Professional,Yes,3.0,10+ Miles,Pacific,39.0,No
4,21940,Married,Male,"90,000",5.0,Graduate Degree,Professional,Yes,0.0,0-1 Miles,North America,47.0,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1251 entries, 0 to 1250
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                1251 non-null   int64
 1   Marital Status    1244 non-null   object
 2   Gender            1238 non-null   object
 3   Income            1243 non-null   object
 4   Children          1238 non-null   float64
 5   Education         1251 non-null   object
 6   Occupation        1251 non-null   object
 7   Home Owner        1247 non-null   object
 8   Cars              1242 non-null   float64
 9   Commute Distance  1251 non-null   object
 10  Region            1251 non-null   object
 11  Age               1238 non-null   float64
 12  Purchased Bike    1251 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 127.2+ KB

In [5]:
# Cambiamos de tipo objeto a float el income
df["Income"] = pd.to_numeric(df["Income"].str.replace(",", ""))

In [6]:
df.describe()

                 ID         Income     Children         Cars          Age
count   1251.000000    1243.000000  1238.000000  1242.000000  1238.000000
mean   20030.208633   56419.951730     1.929725     1.479066    44.058966
std     5331.451777   30992.295354     1.638977     1.121885    11.271138
min    11000.000000   10000.000000     0.000000     0.000000    25.000000
25%    15465.000000   30000.000000     0.000000     1.000000    35.000000
50%    19731.000000   60000.000000     2.000000     1.000000    43.000000
75%    24549.000000   70000.000000     3.000000     2.000000    52.000000
max    29447.000000  170000.000000     5.000000     4.000000    89.000000

In [7]:
# Filtra las filas duplicadas
duplicates = df[df.duplicated(subset=['ID'], keep=False)]

# Ordena las filas duplicadas por el ID
sorted_duplicates = duplicates.sort_values(by='ID')

# Muestra el DataFrame con los duplicados ordenados
sorted_duplicates

,ID,Marital Status,Gender,Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike
764,11225,Married,Female,60000.0,2.0,Partial College,Professional,Yes,1.0,10+ Miles,North America,55.0,No
336,11225,Married,Female,60000.0,2.0,Partial College,Professional,Yes,1.0,10+ Miles,North America,55.0,No
116,11270,Married,Male,130000.0,2.0,Graduate Degree,Management,Yes,3.0,0-1 Miles,North America,42.0,Yes
933,11270,Married,Male,130000.0,2.0,Graduate Degree,Management,Yes,3.0,0-1 Miles,North America,42.0,Yes
13,11270,Married,Male,130000.0,2.0,Graduate Degree,Management,Yes,3.0,0-1 Miles,North America,42.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,29301,Married,Male,80000.0,5.0,Bachelors,Professional,Yes,4.0,1-2 Miles,Pacific,40.0,No
306,29337,Single,Male,30000.0,2.0,Partial College,Clerical,Yes,2.0,5-10 Miles,Pacific,68.0,No
896,29337,Single,Male,30000.0,2.0,Partial College,Clerical,Yes,2.0,5-10 Miles,Pacific,68.0,No
862,29424,Married,Male,10000.0,0.0,Partial High School,Manual,Yes,2.0,0-1 Miles,Europe,32.0,No
122,29424,Married,Male,10000.0,0.0,Partial High School,Manual,Yes,2.0,0-1 Miles,Europe,32.0,No

In [8]:
# Guardamos un nuevo archivo con los duplicados para futuras inspecciones
# antes de eliminarlos
sorted_duplicates.to_csv("bike_buyers_duplicateds.csv", index=False)
# Incluye los que deberiamos quedarnos tambien

In [9]:
# Para eliminar columnas
df = df.drop_duplicates() # Coinciden todos los valores
#df.drop_duplicates(subset=["ID"]) # Valores de movies que se repiten

In [10]:
# Filtra las filas duplicadas
duplicates = df[df.duplicated(subset=['ID'], keep=False)]

# Ordena las filas duplicadas por el ID
sorted_duplicates = duplicates.sort_values(by='ID')

# Muestra el DataFrame con los duplicados ordenados
sorted_duplicates

Empty DataFrame
Columns: [ID, Marital Status, Gender, Income, Children, Education, Occupation, Home Owner, Cars, Commute Distance, Region, Age, Purchased Bike]
Index: []

In [11]:
df.isna().sum()

ID                   0
Marital Status       7
Gender              11
Income               6
Children             8
Education            0
Occupation           0
Home Owner           4
Cars                 9
Commute Distance     0
Region               0
Age                  8
Purchased Bike       0
dtype: int64

In [12]:
# Como son pocos realmente los valores que no tienen algunos datos
# No perdemos mucho asi que los droppeamos
df = df.dropna(subset=["Marital Status","Gender", "Income","Children", "Home Owner", "Cars", "Age"])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 952 entries, 0 to 1249
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                952 non-null    int64
 1   Marital Status    952 non-null    object
 2   Gender            952 non-null    object
 3   Income            952 non-null    float64
 4   Children          952 non-null    float64
 5   Education         952 non-null    object
 6   Occupation        952 non-null    object
 7   Home Owner        952 non-null    object
 8   Cars              952 non-null    float64
 9   Commute Distance  952 non-null    object
 10  Region            952 non-null    object
 11  Age               952 non-null    float64
 12  Purchased Bike    952 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 104.1+ KB

In [14]:
df.to_csv("bike_buyers_clean.csv", index=False)